on:
  push:
    tags:
    - 'v*'
name: Create Release
jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - name: Build project
        id: build_project
        run: |
          ./build.sh
          echo "##[set-output name=deb_waggle_common_tools;]$(ls *.deb)"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset (Waggle Common Tools)
        id: upload-release-asset-waggle-common-tools
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ steps.build_project.outputs.deb_waggle_common_tools }}
          asset_name: ${{ steps.build_project.outputs.deb_waggle_common_tools }}
          asset_content_type: application/vnd.debian.binary-package
